---
- name: Get Release Metadata
  uri:
    url: https://api.github.com/repos/common-fate/granted/releases/{{ release }}
    return_content: yes
  register: release_metadata

- name: Get Release Tag
  shell:
    cmd: jq -r '.tag_name'
    stdin: "{{ release_metadata.content | string }}"
  register: release_tag

- name: Create Temporary Directory
  tempfile:
    state: directory
  register: tempdir

- name: Download Release
  unarchive:
    src: https://releases.commonfate.io/granted/{{ release_tag.stdout }}/granted_{{ release_tag.stdout | replace('v', '') }}_linux_x86_64.tar.gz
    dest: "{{ tempdir.path }}"
    remote_src: yes

- name: Install Release
  copy:
    src: "{{ tempdir.path }}/{{ item }}"
    dest: "{{ bin_dir }}/{{ item }}"
    mode: "0755"
  loop:
    - assume
    - assumego
    - granted

- name: Remove Temporary Directory
  file:
    path: "{{ tempdir.path }}"
    state: absent
