---
# ❯ curl -fsSL https://releases.commonfate.io/granted/v0.5.0/granted_0.5.0_linux_x86_64.tar.gz | tar tzf -
# assume
# assume.bat
# assume.fish
# assume.ps1
# granted
# assumego

- import_tasks: github_repodata.yml
  vars:
    repo: common-fate/granted

- name: Install Archive
  block:
    - debug:
        msg: "Installing {{ tool }} from releases.commonfate.io {{ release_ref }}"

    - import_tasks: install_remote_archive.yml
      vars:
        url: "https://releases.commonfate.io/granted/{{ release_ref }}/granted_{{ release_ref | replace('v', '') }}_linux_x86_64.tar.gz"
        copy:
          - {src: "assume", dest: "{{ bin_dir }}/assume", mode: "0755"}
          - {src: "assumego", dest: "{{ bin_dir }}/assumego", mode: "0755"}
          - {src: "granted", dest: "{{ bin_dir }}/granted", mode: "0755"}

    - set_fact:
        installed_ref: "{{ release_ref }}"
  when: release_ref != installed_ref | default('')
