---
- import_tasks: install_github_archive.yml
  vars:
    repo: ericchiang/pup
    file: pup_{{ release_tag }}_linux_amd64.zip
    copy:
      - {src: "pup", dest: "{{ bin_dir }}/pup", mode: "0755"}
