---
- name: Set Release
  set_fact:
    release_ref: "{{ release }}"
  when: release != 'latest'

- name: Get Release
  block:
    - shell: |
        curl -fsSL https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst | grep -E '^[0-9.]+$' | head -1
      register: latest_release
      changed_when: false

    - set_fact:
        release_ref: "{{ latest_release.stdout }}"
  when: release == 'latest'

- name: Install Package
  block:
    - name: Create Temporary Directory
      tempfile:
        state: directory
      register: tempdir
      changed_when: false

    - name: Download Release
      unarchive:
        src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ release_ref }}.zip"
        dest: "{{ tempdir.path }}"
        remote_src: true
      changed_when: false

    - name: Install
      command:
        argv:
          - ./aws/install
          - --install-dir
          - "{{ opt_dir }}/awscli"
          - --bin-dir
          - "{{ bin_dir }}"
          - --update
      args:
        chdir: "{{ tempdir.path }}"

    - name: Remove Temporary Directory
      file:
        path: "{{ tempdir.path }}"
        state: absent
      changed_when: false

- name: Remove Old Versions
  shell: |
    find {{ opt_dir }}/awscli/v2 -mindepth 1 -maxdepth 1 -type d \! -name "$(basename "$(readlink -f {{ opt_dir }}/awscli/v2/current)")" -print -exec rm -rf '{}' +
  register: find
  changed_when: find.stdout != ""
  failed_when: find.rc != 0
