---
- hosts: localhost
  vars:
    base_dir: "{{ lookup('env', 'HOME') }}/.local"
    bin_dir: "{{ base_dir }}/bin"
    opt_dir: "{{ base_dir }}/opt"
  pre_tasks:
    - name: Disable Restic Backups in {{ bin_dir }}
      file:
        path: "{{ bin_dir }}/.nobackup"
        state: touch
    - name: Disable Restic Backups in {{ opt_dir }}
      file:
        path: "{{ opt_dir }}/.nobackup"
        state: touch
  roles:
    - awscliv2
    - grip
    - hugo
    - jp
    - pup
    - shfmt
    - textql
    - tflint
    - yq
    #- { role: envmgr, envname: Renv, repo: https://github.com/viking/Renv.git }
    #- { role: envmgr, envname: goenv, repo: https://github.com/syndbg/goenv.git }
    #- { role: envmgr, envname: plenv, repo: https://github.com/tokuhirom/plenv.git }
    - { role: envmgr, envname: pyenv, repo: https://github.com/pyenv/pyenv.git }
    #- { role: envmgr, envname: rbenv, repo: https://github.com/rbenv/rbenv.git }
    - { role: envmgr, envname: tfenv, repo: https://github.com/sirhc/tfenv, extra: [terraform] }
    - { role: envmgr, envname: tgenv, repo: https://github.com/cunymatthieu/tgenv.git, extra: [terragrunt] }
