# yamllint disable rule:line-length
---
- hosts: all
  connection: local
  gather_facts: false
  vars:
    base_dir: "{{ lookup('env', 'HOME') }}/.local"
    bin_dir: "{{ base_dir }}/bin"
    man_dir: "{{ base_dir }}/share/man"
    opt_dir: "{{ base_dir }}/opt"
    release: latest  # default, override in individual role calls
    github_metadata_url: "https://api.github.com/repos/{{ repo }}/releases/{{ release }}"
    github_download_url: "https://github.com/{{ repo }}/releases/download/{{ release_ref }}/{{ file }}"
    manifest_file: "{{ lookup('env', 'XDG_CONFIG_HOME') or lookup('env', 'HOME') + '/.config' + '/local-tools-manifest.json' }}"
  vars_files:
    - github_token.yml
  pre_tasks:
    - name: Create Directories
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ base_dir }}"
        - "{{ bin_dir }}"
        - "{{ man_dir }}"
        - "{{ man_dir }}/man1"
        - "{{ opt_dir }}"
        - "{{ base_dir }}/share/zsh/site-functions"
    - name: Disable Restic Backups
      copy:
        content: ""
        dest: "{{ base_dir }}/.nobackup"
        force: false
    - name: Create Manifest File
      copy:
        content: "{}"
        dest: "{{ manifest_file }}"
        force: false
    - name: Gather Package Facts
      package_facts:
        manager: auto
    - name: Install Package Requirements
      dnf:
        name: python3-virtualenv
        state: present
      become: true
      when: "not 'python3-virtualenv' in ansible_facts.packages"
  roles:
    - aws-vault
    - awscliv2
    - b2
    - epy
    - fd
    - gau
    - granted
    - greg
    - grip
    - hugo
    - humblebundle-downloader
    - hwatch
    - jp
    - kb
    - mcfly
    - pup
    - rich
    - shfmt
    - tflint
    - todoist
    - wd
    - yq
