---
- hosts: all
  gather_facts: false
  vars_files:
    - github_token.yml
  pre_tasks:
    - name: Read Manifest
      set_fact:
        manifest: "{{ lookup('file', manifest_file) | from_json }}"
      ignore_errors: true
    - debug: var=manifest verbosity=1
  post_tasks:
    - debug: var=manifest verbosity=1
    - name: Write Manifest
      copy:
        content: "{{ manifest | to_json }}"
        dest: "{{ manifest_file }}"
  roles:
    - common
    - tools
