---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    base_dir: "{{ lookup('env', 'HOME') }}/.local"
    bin_dir: "{{ base_dir }}/bin"
    man_dir: "{{ base_dir }}/share/man"
    opt_dir: "{{ base_dir }}/opt"
    release: latest  # default, override in individual role calls
    github_metadata_url: "https://api.github.com/repos/{{ repo }}/releases/{{ release }}"
    github_download_url: "https://github.com/{{ repo }}/releases/download/{{ tag }}/{{ file }}"
  pre_tasks:
    - name: Create {{ base_dir }} Directory
      file:
        path: "{{ base_dir }}"
        state: directory
        mode: "0755"
    - name: Create {{ bin_dir }} Directory
      file:
        path: "{{ bin_dir }}"
        state: directory
        mode: "0755"
    - name: Create {{ man_dir }} Directory
      file:
        path: "{{ man_dir }}"
        state: directory
        mode: "0755"
    - name: Create {{ man_dir }}/man1 Directory
      file:
        path: "{{ man_dir }}/man1"
        state: directory
        mode: "0755"
    - name: Create {{ opt_dir }} Directory
      file:
        path: "{{ opt_dir }}"
        state: directory
        mode: "0755"
    - name: Create {{ base_dir }}/share/zsh/site-functions Directory
      file:
        path: "{{ base_dir }}/share/zsh/site-functions"
        state: directory
        mode: "0755"
    - name: Disable Restic Backups
      copy:
        content: ""
        dest: "{{ base_dir }}/.nobackup"
        force: false
    - name: Install Package Requirements
      dnf:
        name: python3-virtualenv
        state: present
      become: true
  roles:
    - aws-vault
    - awscliv2
    - b2
    - epy
    - fd
    - gau
    - granted
    - greg
    - grip
    - hugo
    - humblebundle-downloader
    - hwatch
    - jp
    - mcfly
    - pup
    - shfmt
    - tflint
    - todoist
    - wd
    - yq
