---
- hosts: all
  gather_facts: true

  roles:
    - role: common

  tasks:
    # - name: Upgrading Packages
    #   ansible.builtin.dnf:
    #     name: "*"
    #     state: latest
    #     exclude:
    #       - firefox
    #       - firefox-langpacks
    #     download_only: true
    #   become: true

    - name: Installing Tools
      ansible.builtin.include_tasks: "tasks/{{ tool }}.yml"
      loop: "{{ tools }}"
      loop_control:
        loop_var: tool
