---
- name: Finding Latest Release
  include_role:
    name: github
    tasks_from: gh_latest_release

- name: Installing Release from GitHub Archive
  include_role:
    name: install
    tasks_from: remote_archive
  vars:
    url: "{{ gh_download_url }}/{{ file }}"
