---
- name: Finding Latest Release
  include_role:
    name: github
    tasks_from: gh_latest_release
  tags:
    - always

- name: Installing Files from GitHub
  get_url:
    url: "{{ gh_download_url }}/{{ cp.src }}"
    dest: "{{ cp.dest }}"
    mode: "{{ cp.mode }}"
  loop: "{{ copy }}"
  loop_control:
    loop_var: cp
  tags:
    - always
