# https://github.com/junegunn/fzf
---
- name: Installing fzf
  install_from_github:
    repo: junegunn/fzf
    asset_regex: fzf-.*.tar.gz
    version_command: fzf --version
    move_rules:
      - src_regex: fzf
        dst: "{{ bin_dir }}/fzf"
        mode: 0755
