# https://github.com/xtream1101/humblebundle-downloader
---
- name: Installing hbd
  ansible.builtin.pip:
    name: git+https://github.com/xtream1101/humblebundle-downloader
    extra_args: --upgrade
    virtualenv: "{{ opt_dir }}/hbd"

- name: Linking hbd
  ansible.builtin.file:
    src: "{{ opt_dir }}/hbd/bin/hbd"
    dest: "{{ bin_dir }}/hbd"
    state: link
