# https://github.com/johnkerl/miller
---
- name: Installing mlr
  install_from_github:
    repo: johnkerl/miller
    asset_regex: miller-.*.tar.gz
    version_command: mlr --version
    move_rules:
      - src_regex: mlr
        dst: "{{ bin_dir }}/mlr"
        mode: 0755

- name: Installing mlr Man Page
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/johnkerl/miller/main/man/mlr.1
    dest: "{{ man_dir }}/man1/mlr.1"
    mode: 0644
