# https://github.com/Textualize/rich-cli
---
- name: Installing rich
  ansible.builtin.pip:
    name: git+https://github.com/Textualize/rich-cli
    extra_args: --upgrade
    virtualenv: "{{ opt_dir }}/rich-cli"

- name: Linking rich
  ansible.builtin.file:
    src: "{{ opt_dir }}/rich-cli/bin/rich"
    dest: "{{ bin_dir }}/rich"
    state: link
