# https://github.com/terraform-linters/tflint
---
- name: Installing TFLint
  install_from_github:
    repo: terraform-linters/tflint
    asset_regex: tflint_.*.zip
    version_command: tflint --version
    move_rules:
      - src_regex: tflint
        dst: "{{ bin_dir }}/tflint"
        mode: 0755
