---
- import_tasks: install_github_file.yml
  vars:
    repo: sachaos/todoist
    file: todoist_linux_amd64
    dest: todoist

- name: Generate Completion Function
  get_url:
    url: https://raw.githubusercontent.com/urfave/cli/main/autocomplete/zsh_autocomplete  # yamllint disable-line rule:line-length
    dest: "{{ base_dir }}/share/zsh/site-functions/_todoist"
    mode: "0644"
  changed_when: false

- name: Replace $PATH
  replace:
    path: "{{ base_dir }}/share/zsh/site-functions/_todoist"
    regexp: '\$PROG'
    replace: todoist
  changed_when: false
