---
- name: Install Requirements
  dnf:
    name: python3-virtualenv
    state: present
  become: true

- name: Install Module
  pip:
    name: grip
    virtualenv: "{{ opt_dir }}/grip"

- name: Create Link
  file:
    src: "{{ opt_dir }}/grip/bin/grip"
    dest: "{{ bin_dir }}/grip"
    state: link
