---
- name: Create Temporary Directory
  tempfile:
    state: directory
  register: tempdir
  changed_when: false

- name: Download Latest
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: "{{ tempdir.path }}"
    remote_src: true
  when: release == 'latest'

- name: Download Release
  unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ release }}.zip"  # yamllint disable-line rule:line-length
    dest: "{{ tempdir.path }}"
    remote_src: true
  when: release != 'latest'

- name: Install
  command:
    argv:
      - ./aws/install
      - --install-dir
      - "{{ opt_dir }}/awscli"
      - --bin-dir
      - "{{ bin_dir }}"
      - --update
  args:
    chdir: "{{ tempdir.path }}"

- name: Remove Temporary Directory
  file:
    path: "{{ tempdir.path }}"
    state: absent
  changed_when: false
