---
- import_tasks: install_github_file.yml
  vars:
    repo: Backblaze/B2_Command_Line_Tool
    file: b2-linux
    dest: b2

- name: Install Completion Function
  get_url:
    url: https://raw.githubusercontent.com/Backblaze/B2_Command_Line_Tool/master/contrib/bash_completion/b2
    dest: "{{ base_dir }}/share/zsh/site-functions/_b2"
    mode: "0644"

# - name: Add zsh compdef Line
#   lineinfile:
#     path: "{{ base_dir }}/share/zsh/site-functions/_b2"
#     insertbefore: BOF
#     line: "#compdef b2"
