---
- name: Get Release Metadata
  uri:
    url: https://api.github.com/repos/jmespath/jp/releases/{{ release }}
    return_content: true
  register: release_metadata

- name: Get Release URL
  shell:
    cmd: jq -r '.assets[] | select(.browser_download_url | match("linux-amd64$")) | .browser_download_url'  # yamllint disable-line rule:line-length
    stdin: "{{ release_metadata.content | string }}"
  register: release_url

- name: Download Release
  get_url:
    url: "{{ release_url.stdout }}"
    dest: "{{ bin_dir }}/jp"
    mode: "0755"
