---
- import_tasks: install_github_archive.yml
  vars:
    repo: terraform-linters/tflint
    file: tflint_linux_amd64.zip
    copy:
      - {src: "tflint", dest: "{{ bin_dir }}/tflint", mode: "0755"}
