# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
---
- block:
    - name: Installing AWS CLI v2
      include_role:
        name: install
        tasks_from: remote_archive
      vars:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        commands:
          - [./aws/install, --install-dir, "{{ opt_dir }}/awscli", --bin-dir, "{{ bin_dir }}", --update]

    - name: Removing Old Versions of AWS CLI v2
      shell: |
        find '{{ opt_dir }}/awscli/v2' -mindepth 1 -maxdepth 1 -type d \! -name "$(basename "$(readlink -f {{ opt_dir }}/awscli/v2/current)")" -print -exec rm -rf '{}' +
      register: find
      changed_when: find.stdout != ""
      failed_when: find.rc != 0
  tags:
    - awscliv2
