# https://github.com/xtream1101/humblebundle-downloader
---
- name: Installing Humble Bundle Downloader
  include_role:
    name: install
    tasks_from: pip
  vars:
    module:
      - git+https://github.com/xtream1101/humblebundle-downloader
    env: hbd
    cmd: hbd
