# https://gohugo.io/
---
- name: Installing Hugo
  include_role:
    name: github
    tasks_from: gh_install_archive
  vars:
    repo: gohugoio/hugo
    file: hugo_{{ gh_release_tag | replace('v', '') }}_Linux-64bit.tar.gz
    copy:
      - src: "hugo"
        dest: "{{ bin_dir }}/hugo"
        mode: "0755"
  tags:
    - hugo
