# https://github.com/blacknon/hwatch
---
- name: Installing hwatch - alternative watch command
  include_role:
    name: github
    tasks_from: gh_install_archive
  vars:
    repo: blacknon/hwatch
    file: hwatch-{{ gh_release_tag }}.x86_64-unknown-linux-gnu.tar.gz
    copy:
      - src: "bin/hwatch"
        dest: "{{ bin_dir }}/hwatch"
        mode: "0755"
      - src: "man/hwatch.1"
        dest: "{{ man_dir }}/man1/hwatch.1"
        mode: "0644"
      - src: "completion/zsh/_hwatch"
        dest: "{{ data_dir }}/zsh/site-functions/_hwatch"
        mode: "0644"
