---
- import_tasks: install_github_files.yml
  vars:
    repo: sachaos/todoist
    copy:
      - {src: "todoist_linux_amd64", dest: "{{ bin_dir }}/todoist", mode: "0755"}

- name: Generate Completion Function
  get_url:
    url: https://raw.githubusercontent.com/urfave/cli/main/autocomplete/zsh_autocomplete
    dest: "{{ data_dir }}/zsh/site-functions/_todoist"
    mode: "0644"
  changed_when: false

- name: Replace $PATH
  replace:
    path: "{{ data_dir }}/zsh/site-functions/_todoist"
    regexp: '\$PROG'
    replace: todoist
  changed_when: false
