# https://github.com/jqlang/jq
---
- name: Installing jq
  include_role:
    name: github
    tasks_from: gh_install_files
  vars:
    repo: jqlang/jq
    copy:
      - src: "jq-linux-amd64"
        dest: "{{ bin_dir }}/jq"
        mode: "0755"
  tags:
    - jq
