# https://github.com/gnebbia/kb
---
- name: Installing kb - minimalist knowledge base manager
  include_role:
    name: install
    tasks_from: pip
  vars:
    module:
      - git+https://github.com/gnebbia/kb
      - colored<2.2.0
    env: kb
    cmd: kb
  tags:
    - kb
