# https://github.com/FiloSottile/mkcert
---
- name: Installing mkcert
  include_role:
    name: github
    tasks_from: gh_install_files
  vars:
    repo: FiloSottile/mkcert
    copy:
      - src: "mkcert-{{ gh_release_tag }}-linux-amd64"
        dest: "{{ bin_dir }}/mkcert"
        mode: "0755"
  tags:
    mkcert
