# https://github.com/johnkerl/miller
---
- name: Installing Miller
  include_role:
    name: github
    tasks_from: gh_install_archive
  vars:
    repo: johnkerl/miller
    file: miller-{{ gh_release_tag | replace('v', '') }}-linux-amd64.tar.gz
    copy:
      - src: "miller-{{ gh_release_tag | replace('v', '') }}-linux-amd64/mlr"
        dest: "{{ bin_dir }}/mlr"
        mode: "0755"

- name: Installing Miller - man page
  get_url:
    url: https://raw.githubusercontent.com/johnkerl/miller/main/man/mlr.1
    dest: "{{ man_dir }}/man1/mlr.1"
    mode: "0644"
