# https://github.com/johnkerl/miller
---
- name: Installing Miller
  include_role:
    name: github
    tasks_from: gh_install_archive
  vars:
    repo: johnkerl/miller
    file: miller-{{ gh_release_tag | replace('v', '') }}-linux-amd64.tar.gz
    copy:
      - src: "miller-{{ gh_release_tag | replace('v', '') }}-linux-amd64/mlr"
        dest: "{{ bin_dir }}/mlr"
        mode: "0755"
