# https://github.com/mvdan/sh
---
- name: Installing shfmt
  include_role:
    name: github
    tasks_from: gh_install_files
  vars:
    repo: mvdan/sh
    copy:
      - src: "shfmt_{{ gh_release_tag }}_linux_amd64"
        dest: "{{ bin_dir }}/shfmt"
        mode: "0755"
