# https://github.com/terraform-linters/tflint
---
- name: Installing TFLint
  include_role:
    name: github
    tasks_from: gh_install_archive
  vars:
    repo: terraform-linters/tflint
    file: tflint_linux_amd64.zip
    copy:
      - src: "tflint"
        dest: "{{ bin_dir }}/tflint"
        mode: "0755"
