# https://github.com/mikefarah/yq
---
- name: Installing yq
  include_role:
    name: github
    tasks_from: gh_install_files
  vars:
    repo: mikefarah/yq
    copy:
      - src: "yq_linux_amd64"
        dest: "{{ bin_dir }}/yq"
        mode: "0755"
  tags:
    - yq
