---
- name: Install Requirements
  dnf:
    name: golang-bin
    state: present
  become: yes

- name: Create Temporary Directory
  tempfile:
    state: directory
  register: tempdir

- name: Build
  command:
    cmd: go get -u github.com/dinedal/textql/...
  environment:
    GOPATH: "{{ tempdir.path }}"

- name: Install
  copy:
    src: "{{ tempdir.path }}/bin/textql"
    dest: "{{ bin_dir }}/textql"
    mode: "0755"

# Go has the annoying habit of removing the write on files, making it annoying
# to remove temporary builds.
- name: Set Permissions
  file:
    dest: "{{ tempdir.path }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: Remove Temporary Directory
  file:
    path: "{{ tempdir.path }}"
    state: absent
