---
- name: Creating Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ local_dir }}"
    - "{{ bin_dir }}"
    - "{{ opt_dir }}"
    - "{{ data_dir }}"
    - "{{ data_dir }}/zsh/site-functions"
    - "{{ man_dir }}"
    - "{{ man_dir }}/man1"

- name: Disabling Restic Backups
  copy:
    content: ""
    dest: "{{ local_dir }}/.nobackup"
    force: false

- name: Gathering Package Facts
  package_facts:
    manager: auto
