---
- name: Create Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ local_dir }}"
    - "{{ bin_dir }}"
    - "{{ opt_dir }}"
    - "{{ data_dir }}"
    - "{{ data_dir }}/zsh/site-functions"
    - "{{ man_dir }}"
    - "{{ man_dir }}/man1"

- name: Disable Restic Backups
  copy:
    content: ""
    dest: "{{ local_dir }}/.nobackup"
    force: false

- name: Gather Package Facts
  package_facts:
    manager: auto

- name: Install Package Requirements
  dnf:
    name: python3-virtualenv
    state: present
  become: true
  when: "not 'python3-virtualenv' in ansible_facts.packages"
