---
- name: Get Release Metadata
  uri:
    url: https://api.github.com/repos/99designs/aws-vault/releases/{{ release }}
    return_content: yes
  register: release_metadata

- name: Get Release Tag
  shell:
    cmd: jq -r '.tag_name'
    stdin: "{{ release_metadata.content | string }}"
  register: release_tag

- name: Download Release
  get_url:
    url: https://github.com/99designs/aws-vault/releases/download/{{ release_tag.stdout }}/aws-vault-linux-amd64
    dest: "{{ bin_dir }}/aws-vault"
    mode: "0755"
