---
- import_tasks: install_github_file.yml
  vars:
    repo: 99designs/aws-vault
    file: aws-vault-linux-amd64
    dest: aws-vault

- name: Generate Completion Function
  command: "{{ bin_dir }}/aws-vault --completion-script-zsh"
  register: completion
  changed_when: false

- name: Create Completion Function
  copy:
    dest: "{{ base_dir }}/share/zsh/site-functions/_aws-vault"
    content: "{{ completion.stdout }}"
