---
- name: Get Release Metadata
  uri:
    url: https://api.github.com/repos/sharkdp/fd/releases/{{ release }}
    return_content: yes
  register: release_metadata

- name: Get Release Tag
  shell:
    cmd: jq -r '.tag_name'
    stdin: "{{ release_metadata.content | string }}"
  register: release_tag

- name: Create Temporary Directory
  tempfile:
    state: directory
  register: tempdir

- name: Download Release
  unarchive:
    src: https://github.com/sharkdp/fd/releases/download/{{ release_tag.stdout }}/fd-{{ release_tag.stdout }}-x86_64-unknown-linux-gnu.tar.gz
    dest: "{{ tempdir.path }}"
    remote_src: yes

- name: Install Command
  copy:
    src: "{{ tempdir.path }}/fd-{{ release_tag.stdout }}-x86_64-unknown-linux-gnu/fd"
    dest: "{{ bin_dir }}/fd"
    mode: "0755"

- name: Install Man Page
  copy:
    src: "{{ tempdir.path }}/fd-{{ release_tag.stdout }}-x86_64-unknown-linux-gnu/fd.1"
    dest: "{{ man_dir }}/man1/fd.1"
    mode: "0644"

- name: Install Completion Function
  copy:
    src: "{{ tempdir.path }}/fd-{{ release_tag.stdout }}-x86_64-unknown-linux-gnu/autocomplete/_fd"
    dest: "{{ base_dir }}/share/zsh/site-functions/_fd"
    mode: "0644"

- name: Remove Temporary Directory
  file:
    path: "{{ tempdir.path }}"
    state: absent
