---
- import_tasks: install_github_archive.yml
  vars:
    repo: sharkdp/fd
    file: fd-{{ release_tag }}-x86_64-unknown-linux-gnu.tar.gz
    path: fd-{{ release_tag }}-x86_64-unknown-linux-gnu
    copy:
      - {src: "{{ path }}/fd", dest: "{{ bin_dir }}/fd", mode: "0755"}
      - {src: "{{ path }}/fd.1", dest: "{{ man_dir }}/man1/fd.1", mode: "0644"}
      - {src: "{{ path }}/autocomplete/_fd", dest: "{{ base_dir }}/share/zsh/site-functions/_fd", mode: "0644"}  # yamllint disable-line rule:line-length
