---
- name: Installing Module
  community.general.gem:
    bindir: "{{ bin_dir }}"
    install_dir: "{{ opt_dir }}/{{ env }}"
    name: "{{ name }}"
    repository: "{{ repo }}"
    state: latest
    user_install: false
