---
- name: Installing Module
  pip:
    name: "{{ module }}"
    virtualenv: "{{ opt_dir }}/{{ env }}"

- name: Creating Link
  file:
    src: "{{ opt_dir }}/{{ env }}/bin/{{ cmd }}"
    dest: "{{ bin_dir }}/{{ cmd }}"
    state: link
