---
- block:
    - name: Creating Temporary Directory
      tempfile:
        state: directory
      register: tempdir
      changed_when: false

    - name: Downloading Archive
      unarchive:
        src: "{{ url }}"
        dest: "{{ tempdir.path }}"
        remote_src: true
      changed_when: false

    - name: Copying Files
      copy:
        remote_src: true
        src: "{{ tempdir.path }}/{{ cp.src }}"
        dest: "{{ cp.dest }}"
        mode: "{{ cp.mode }}"
      loop: "{{ copy }}"
      loop_control:
        loop_var: cp
      when: (copy | default([]))

    - name: Running Commands
      command:
        argv: command
      args:
        chdir: "{{ tempdir.path }}"
      loop: "{{ commands }}"
      loop_control:
        loop_var: command
      when: (commands | default([]))

    - name: Removing Temporary Directory
      file:
        path: "{{ tempdir.path }}"
        state: absent
      changed_when: false
  tags:
    - always
